import type { RankDefinition } from './types';

export const ranks: RankDefinition[] = [
  {
    id: 'recruit',
    name: 'Рекрут',
    requirement: {},
    cost: {},
    bonus: {},
  },
  {
    id: 'soldier',
    name: 'Солдат',
    requirement: {"reputation": 3, "discipline": 2},
    cost: {"time": 1},
    bonus: {"discipline": 1},
  },
  {
    id: 'senior_soldier',
    name: 'Старший солдат',
    requirement: {"reputation": 4, "discipline": 3},
    cost: {"time": 2},
    bonus: {"documents": 1, "reputation": 1},
  },
  {
    id: 'junior_sergeant',
    name: 'Молодший сержант',
    requirement: {"reputation": 5, "discipline": 3, "documents": 1},
    cost: {"time": 2},
    bonus: {"discipline": 1, "tech": 1},
  },
  {
    id: 'sergeant',
    name: 'Сержант',
    requirement: {"reputation": 6, "discipline": 4},
    cost: {"time": 1, "documents": 1},
    bonus: {"reputation": 1, "tech": 1},
  },
  {
    id: 'senior_sergeant',
    name: 'Старший сержант',
    requirement: {"reputation": 7, "discipline": 5},
    cost: {"time": 2},
    bonus: {"discipline": 1, "reputation": 1},
  },
  {
    id: 'chief_sergeant',
    name: 'Головний сержант',
    requirement: {"reputation": 8, "discipline": 6, "documents": 1},
    cost: {"time": 2},
    bonus: {"tech": 1, "reputation": 1},
  },
  {
    id: 'staff_sergeant',
    name: 'Штаб-сержант',
    requirement: {"reputation": 9, "discipline": 7},
    cost: {"time": 2, "documents": 1},
    bonus: {"tech": 1, "reputation": 1},
  },
  {
    id: 'master_sergeant',
    name: 'Майстер-сержант',
    requirement: {"reputation": 10, "discipline": 7},
    cost: {"time": 2},
    bonus: {"documents": 1, "reputation": 1},
  },
  {
    id: 'senior_master_sergeant',
    name: 'Старший майстер-сержант',
    requirement: {"reputation": 11, "discipline": 8},
    cost: {"time": 2, "tech": 1},
    bonus: {"documents": 1, "reputation": 1},
  },
  {
    id: 'chief_master_sergeant',
    name: 'Головний майстер-сержант',
    requirement: {"reputation": 12, "discipline": 9},
    cost: {"time": 2},
    bonus: {"tech": 1, "reputation": 1},
  },
  {
    id: 'junior_lieutenant',
    name: 'Молодший лейтенант',
    requirement: {"reputation": 13, "discipline": 10, "documents": 1},
    cost: {"time": 2, "documents": 1},
    bonus: {"tech": 1, "reputation": 1},
  },
  {
    id: 'lieutenant',
    name: 'Лейтенант',
    requirement: {"reputation": 14, "discipline": 10},
    cost: {"time": 2},
    bonus: {"documents": 1, "reputation": 1},
  },
  {
    id: 'senior_lieutenant',
    name: 'Старший лейтенант',
    requirement: {"reputation": 15, "discipline": 11},
    cost: {"time": 2, "tech": 1},
    bonus: {"documents": 1, "reputation": 1},
  },
  {
    id: 'captain',
    name: 'Капітан',
    requirement: {"reputation": 16, "discipline": 12},
    cost: {"time": 2},
    bonus: {"tech": 1, "reputation": 1},
  },
  {
    id: 'major',
    name: 'Майор',
    requirement: {"reputation": 17, "discipline": 13, "tech": 1},
    cost: {"time": 2},
    bonus: {"documents": 1, "reputation": 1},
  },
  {
    id: 'lieutenant_colonel',
    name: 'Підполковник',
    requirement: {"reputation": 18, "discipline": 14},
    cost: {"time": 2, "documents": 1},
    bonus: {"tech": 1, "reputation": 1},
  },
  {
    id: 'colonel',
    name: 'Полковник',
    requirement: {"reputation": 19, "discipline": 15},
    cost: {"time": 2},
    bonus: {"documents": 1, "reputation": 1},
  },
  {
    id: 'brigadier_general',
    name: 'Бригадний генерал',
    requirement: {"reputation": 20, "discipline": 16, "tech": 1},
    cost: {"time": 2, "tech": 1},
    bonus: {"documents": 1, "reputation": 1},
  },
  {
    id: 'major_general',
    name: 'Генерал-майор',
    requirement: {"reputation": 21, "discipline": 17},
    cost: {"time": 2},
    bonus: {"tech": 1, "reputation": 1},
  },
  {
    id: 'lieutenant_general',
    name: 'Генерал-лейтенант',
    requirement: {"reputation": 22, "discipline": 18},
    cost: {"time": 2, "documents": 1},
    bonus: {"tech": 1, "reputation": 1},
  },
  {
    id: 'general',
    name: 'Генерал',
    requirement: {"reputation": 23, "discipline": 19},
    cost: {"time": 2, "tech": 1},
    bonus: {},
    victory: true,
  },
];

export const GENERAL_RANK_ID = 'general';
