import { createJojMoves } from '../src/game/moves';
import {
  drawCardHandler,
  endTurnHandler,
  passHandler,
  playCardHandler,
  playLegendaryCardHandler,
  promoteHandler,
  resolveDrawAutoCardHandler,
} from '../src/game/moveHandlers';
import type { JojMovesDeps, MoveArgs } from '../src/game/moveTypes';
import type { CardDefinition, JojGameState } from '../src/game/types';
import { createEmptyGameState } from '../src/game/stateFactory';

export {
  createEmptyGameState,
  createJojMoves,
  drawCardHandler,
  endTurnHandler,
  passHandler,
  playCardHandler,
  playLegendaryCardHandler,
  promoteHandler,
  resolveDrawAutoCardHandler,
};
export type { CardDefinition, JojMovesDeps, JojGameState, MoveArgs };

export const makeState = (): JojGameState => ({
  gameMode: 'standard',
  deck: [],
  discard: [],
  legendaryDeck: [],
  legendaryDiscard: [],
  legendaryDraftCompleted: { '0': true, '1': true },
  systemMessageSeq: 0,
  playerNames: { '0': 'P1', '1': 'P2' },
  chat: [],
  players: {
    '0': {
      hand: [],
      rankId: 'recruit',
      resources: {
        time: 1,
        reputation: 1,
        discipline: 1,
        documents: 1,
        tech: 1,
      },
    },
    '1': {
      hand: [],
      rankId: 'recruit',
      resources: {
        time: 1,
        reputation: 1,
        discipline: 1,
        documents: 1,
        tech: 1,
      },
    },
  },
  hands: { '0': [], '1': [] },
  legendaryHands: { '0': [], '1': [] },
  ranks: { '0': 'recruit', '1': 'recruit' },
  rankImageByPlayer: {},
  resources: {
    '0': { time: 1, reputation: 1, discipline: 1, documents: 1, tech: 1 },
    '1': { time: 1, reputation: 1, discipline: 1, documents: 1, tech: 1 },
  },
  promotedThisTurn: { '0': false, '1': false },
  lyapScandalShieldUntilTurn: { '0': 0, '1': 0 },
  extraHandPlayTokens: { '0': 0, '1': 0 },
  sukhpayZsuWatchUntilTurn: { '0': 0, '1': 0 },
  sukhpayZsuPendingBonus: { '0': false, '1': false },
  gameStats: {
    turnsCompleted: 0,
    resourcesGainedTotal: 0,
    resourcesLostTotal: 0,
    resourcesGainedByType: {
      time: 0,
      reputation: 0,
      discipline: 0,
      documents: 0,
      tech: 0,
    },
    resourcesLostByType: {
      time: 0,
      reputation: 0,
      discipline: 0,
      documents: 0,
      tech: 0,
    },
    lyapsPlayedOnOthers: 0,
    scandalsPlayedOnOthers: 0,
  },
  noPlayablePassStreak: 0,
  endGameVote: { active: false, requestedBy: null, votes: {} },
  pendingDrawAutoResolution: null,
});

export const makeDeps = (
  overrides: Partial<JojMovesDeps> = {},
): JojMovesDeps => ({
  INVALID_MOVE: 'INVALID_MOVE',
  DRAW_STAGE: 'draw',
  PLAY_STAGE: 'play',
  END_STAGE: 'end',
  HAND_LIMIT: 8,
  resourceKeys: [
    'time',
    'reputation',
    'discipline',
    'documents',
    'tech',
  ] as const,
  resourceLabelsUk: {
    time: 'Час',
    reputation: 'Авторитет',
    discipline: 'Дисципліна',
    documents: 'Документи',
    tech: 'Технології',
  },
  canPlayHandCardAtStage: () => true,
  appendChat: () => undefined,
  nextSystemMessageSeq: () => 1,
  getPlayerLabel: (_G: JojGameState, playerID: string) => playerID,
  syncPlayerState: (state: JojGameState, playerID: string) => {
    state.players[playerID].resources = { ...state.resources[playerID] };
    state.players[playerID].rankId = state.ranks[playerID];
    state.players[playerID].hand = state.hands[playerID];
  },
  isProtectedFromLyapScandal: () => false,
  triggerSukhpayZsuOnScandal: () => undefined,
  applyCardEffects: () => true,
  applyCardEffectsSoft: () => ({ resources: {}, rank: 0 }),
  getReplacementUnitsForCard: () => 0,
  summarizeAppliedDiff: () => ({ resources: {}, rank: 0 }),
  effectSummaryToText: () => 'ok',
  resourceDeltaToText: () => 'ok',
  categoryLabelUk: () => 'SCANDAL',
  cardFlavorSnippet: () => '',
  rankNameById: (rankId: string) => rankId,
  buildLyapSystemMessage: () => '',
  buildScandalSystemMessage: () => '',
  buildSupportSystemMessage: () => '',
  buildPlayedLyapSystemMessage: () => '',
  buildPlayedScandalSystemMessage: () => '',
  buildPlayedDecisionSystemMessage: () => '',
  buildVvnzRankSystemMessage: () => '',
  buildPromotionSystemMessage: () => '',
  buildLegendaryPlayedMessageText: () => '',
  legendaryTexts: {
    budanovCanceled: () => '',
    budanovNoTarget: () => '',
    starlinkCanceled: () => '',
    starlinkNoTarget: () => '',
    sukhpayActivated: () => '',
    grammarShield: () => '',
    posmishkaMalyuka: () => '',
    statueTor: () => '',
    churchLeadership: () => '',
    waterRestore: () => '',
    goodPressOfficerGranted: () => '',
    goodPressOfficerNoChange: () => '',
    droidDemote: () => '',
  } as JojMovesDeps['legendaryTexts'],
  clampNonNegativeResources: () => undefined,
  snapshotResourcesForStats: (G: JojGameState) => ({
    '0': { ...G.resources['0'] },
    '1': { ...G.resources['1'] },
  }),
  recordResourceFlowStats: () => undefined,
  resetNoPlayablePassStreak: () => undefined,
  shouldCountNoPlayablePass: () => false,
  hasPlayableCardsByInventory: () => false,
  incrementNoPlayablePassStreak: () => undefined,
  incrementTurnsCompleted: () => undefined,
  incrementLyapPlayedOnOthers: () => undefined,
  incrementScandalPlayedOnOthers: () => undefined,
  resetEndGameVote: () => undefined,
  computeShieldUntilNextOwnTurn: () => 0,
  cancelLastLyapOrScandalForPlayer: () => ({
    canceledCard: null,
    summary: { resources: {}, rank: 0 },
  }),
  cancelLastScandalForPlayer: () => ({
    canceledCard: null,
    summary: { resources: {}, rank: 0 },
  }),
  promoteToSpecificRank: () => ({ ok: false }),
  grantSpecificRankIgnoringRequirements: () => ({ ok: false, reason: 'nope' }),
  demoteByOneRankWithSeatCheck: () => ({ ok: false, reason: 'nope' }),
  promoteRank: () => false,
  getActiveRanks: () => [{ id: 'recruit' }],
  ...overrides,
});
